#!/bin/sh
#
# Parse lsscsi -g o/p to build a drive/library config for the 'vxlibrary'
# daemon.
#
# Designed to be called from vtl rc script
#
# * Copyright (C) 2005 Mark Harvey markh794 at gmail dot com
# *                                mark_harvey at symantec dot com
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

export PATH=/usr/bin:$PATH

if [ $# != 1 ]; then
	echo "Usage: $0 username"
	exit 1
fi

USER=$1
TMP=/var/tmp/_build.$$
CONFIG=/etc/vtl/vxlib.conf
DRIVECONFIG=/etc/vtl/device.conf
LIBCONTENTS=/etc/vtl/library_contents
OPTIONS=""

# rc script will make sure this exists...
. /etc/vtl/vtl.conf

if [ $VERBOSE -gt 0 ];then
	OPTIONS="-v"
fi

if [ ! -f $DRIVECONFIG ]; then
	echo "Sorry, Can't continue - no $DRIVECONFIG"
	exit 1
fi

# Test for new interface to dynamically add logical units.
if [ ! -f /sys/bus/pseudo/drivers/vtl/add_lu ]; then
	echo "Sorry, Can't continue - No kernel module loaded or out of date ??"
	echo "Please visit http://linuxvtl.googlepages.com for latest release"
	exit 1
fi

# OK, we know the module is loaded..
MAJOR=`grep vtl /proc/devices|awk '{print $1}'`

# First we need to setup & configure drives.
# Once all the drives are setup, query devices for config &
# build library structure based on information found.
count=`grep ^Drive $LIBCONTENTS|wc -l`

for a in `seq $count`
do
	grep "^Drive $a" $DRIVECONFIG

	# Make sure device node exists..
	# A better bet would be to configure udev...
	if [ ! -c /dev/vtl$count ]; then
		if [ -a /dev/vtl$count ]; then
			# Exists but not a char device... remove..
			rm /dev/vtl$count
		fi
		mknod /dev/vtl$count c $major $count
		chown vtl:vtl /dev/vtl$count
	fi

	# Start daemon for new lu
	vtltape -q $a
done

# now start the library daemon
vtllibrary -q 0

rm -f $TMP

