.TH make_vtl_devices "1" "July 2009" "mhvtl 0.10" "User Commands"
.SH NAME
make_vtl_devices \- Part of helper scripts to start VTL subsystem.
.SH SYNOPSIS
.B make_vtl_devices userName
.SH DESCRIPTION
.\" Add any additional description here
.PP
Invoked from /etc/init.d/mhvtl. Should not be run manually.
Responsible for creating device nodes for mhvtl kernel module interface.
.SH AUTHOR
Written by Mark Harvey
.SH BUGS
Not documented.
.SH "REPORTING BUGS"
Report bugs to <markh794@gmail.com> <mark_harvey@symantec.com>.
.SH COPYRIGHT
Copyright \(co 2005 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR library_contents(5),
.BR build_library_config(1),
.BR mktape(1),
.BR mhvtl(1),
.BR vtlcmd(1),
.BR vtllibrary(1),
.BR vtltape(1)
