.TH mhvtl.conf "5" "July 2009" "vtl 0.16" "User Commands"
.SH NAME
mhvtl.conf \- Configuration file for
.BR vtllibrary(1)
and
.BR vtltape(1)
.SH DESCRIPTION
.\" Add any additional description here
.PP
Configuration file to define startup behaviour of the vtl.

.IP
CAPACITY = XXX

Defines default capacity any new media will be created (in Megabytes).

.IP
VERBOSE = [0|1] Enable verbose logging at startup.

.IP
DEBUG = [0|1] Enable debug logging

.SH AUTHOR
Written by Mark Harvey
.SH BUGS
.RS
This man page.
.RE
.RS
No version information.
.RE
.RS
Config file not xml.
.RE
.RS
.BR vtllibrary(1)
needs to be restarted to read any changes made.
.RE
.SH "REPORTING BUGS"
Report bugs to <markh794@gmail.com> <mark_harvey@symantec.com>.
.SH COPYRIGHT
Copyright \(co 2005 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR build_library_config(1),
.BR mktape(1),
.BR mhvtl(1),
.BR vtlcmd(1),
.BR vtllibrary(1),
.BR vtltape(1)
