.TH mhvtl.conf "5" "September 2011" "mhvtl 1.0" "User Commands"
.SH NAME
mhvtl.conf \- Configuration file for
.BR vtllibrary(1)
and
.BR vtltape(1)
.SH DESCRIPTION
.\" Add any additional description here
.PP
Configuration file to define startup behaviour of the vtl.

.IP
CAPACITY = XXX

Defines default capacity any new media will be created (in Megabytes).

make_vtl_media(1) uses this value and passes to 'mktape'

.IP
VERBOSE = [0|1|2|3] Define daemon logging level at startup.
Refer
.BR vtlcmd(1)
to adjust logging level at runtime.

.IP
DEBUG = [0|1] Disable/Enable kernel module logging. Can be enabled/disabled
at runtime via
.IP
"echo 0 > /sys/bus/pseduo/drivers/mhvtl/opts" to disable, or
.IP
"echo 1 > /sys/bus/pseudo/drivers/mhvtl/opts" to enable logging.

.SH AUTHOR
Written by Mark Harvey

.SH BUGS
This man page.
.PP
Config file not xml.
.PP
.BR vtllibrary(1)
needs to be restarted to read any changes made. (By design).
.PP

.SH "REPORTING BUGS"
Report bugs to <markh794@gmail.com> <mark_harvey@symantec.com>.

.SH COPYRIGHT
Copyright \(co 2005 Free Software Foundation, Inc.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR build_library_config(1),
.BR mktape(1),
.BR mhvtl(1),
.BR vtlcmd(1),
.BR vtllibrary(1),
.BR vtltape(1)
