#
# mhvtl.conf
#

# Home directory for tape emulation files
MHVTL_HOME_PATH=/opt/mhvtl/test
MHVTL_CONFIG_PATH=/etc/mhvtl/test

# Default media capacity (500 M)
CAPACITY=10000

# Set default verbosity [0-9]
VERBOSE=9

# Set kernel module debugging [0|1]
VTL_DEBUG=1

# vtltape and vtllibrary debugging [Blank or -d]
DAEMON_DEBUG=-d
